-- ==============================================================================
-- 🏫 [푸르고 드림 / Puleo Dream] Supabase 올인원 데이터베이스 통합 스키마 (최신 업데이트 반영)
-- 
-- 주요 업데이트 내역:
-- 1. 수학 그래프 도구 및 손글씨 연습장(drawing_data, graph_data) 제거 반영
-- 2. 친구들의 다양한 풀이 제거 및 표준 단계별 풀이/사진 첨부 구조로 최적화
-- 3. 교과서 문제, Q&A, 오답노트, 단원평가, 탐구 포스터 등 전 테이블 스키마 정비
-- 
-- 사용 방법:
-- 1. Supabase 대시보드(https://supabase.com/dashboard) 로그인 후 프로젝트 선택
-- 2. 왼쪽 메뉴에서 [SQL Editor] 클릭 -> [+ New query] 클릭
-- 3. 아래 SQL 코드를 복사하여 붙여넣고 [Run] (또는 Ctrl+Enter) 버튼 클릭!
-- ==============================================================================

-- 확장 기능 활성화
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==============================================================================
-- 1. 회원 계정 테이블 (user_accounts)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.user_accounts (
  id TEXT PRIMARY KEY,                                      -- 고유 계정 ID (예: user-1741234567-abcde)
  login_id TEXT UNIQUE NOT NULL,                            -- 로그인 아이디
  password_hash TEXT NOT NULL,                              -- 비밀번호
  role TEXT NOT NULL DEFAULT 'student',                     -- 역할: 'student', 'teacher', 'admin'
  nickname TEXT NOT NULL,                                   -- 닉네임 또는 성함
  school_name TEXT DEFAULT '대구화원고등학교',               -- 학교명
  grade TEXT DEFAULT 'high_1',                              -- 학년 ('high_1', 'high_2', 'high_3')
  avatar_seed TEXT DEFAULT 'student_avatar',                -- 프로필 아바타 시드
  created_at TIMESTAMPTZ DEFAULT now(),                     -- 가입 일시
  updated_at TIMESTAMPTZ DEFAULT now()                      -- 정보 수정 일시
);

COMMENT ON TABLE public.user_accounts IS '학생 및 관리자/선생님 회원 계정 정보';

-- ==============================================================================
-- 2. 교과서 문제 은행 테이블 (textbook_problems)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.textbook_problems (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 문제 고유 번호
  textbook_id TEXT NOT NULL,                                -- 교과서 식별자 (예: math-high1-miraen)
  subject TEXT NOT NULL,                                    -- 과목: 'math' (수학), 'science' (과학)
  grade TEXT DEFAULT 'high_1',                              -- 대상 학년
  chapter TEXT NOT NULL,                                    -- 대단원명
  unit_number TEXT,                                         -- 중단원 번호
  unit_name TEXT NOT NULL,                                  -- 중단원/소단원명
  sub_unit_id TEXT,                                         -- 소단원 코드
  unit_code TEXT,                                           -- 단원 연계 코드 (예: M1-01, S1-01)
  page_number INTEGER DEFAULT 1,                            -- 교과서 쪽수
  problem_number TEXT NOT NULL,                             -- 교과서 문제 번호
  problem_type TEXT DEFAULT '개념확인',                      -- 문제 유형
  difficulty TEXT DEFAULT '보통',                            -- 난이도 ('기초', '보통', '심화', '고난도')
  problem_text TEXT NOT NULL,                               -- 문제 지문 및 발문
  solution_steps JSONB DEFAULT '[]'::jsonb,                 -- 단계별 친절한 풀이 과정 (JSON 배열)
  final_answer TEXT NOT NULL,                               -- 최종 정답
  core_concepts JSONB DEFAULT '[]'::jsonb,                  -- 핵심 공식 및 연계 개념 목록
  dream_tip TEXT,                                           -- 푸르고 마스코트의 꿀팁 / 주의할 실수
  solution_image TEXT,                                      -- 해설/풀이 사진 (Base64 또는 URL)
  views INTEGER DEFAULT 0,                                  -- 학생 조회수
  likes INTEGER DEFAULT 0,                                  -- 학생 추천수
  created_at TIMESTAMPTZ DEFAULT now()                      -- 문제 등록 일시
);

COMMENT ON TABLE public.textbook_problems IS '수학·과학 교과서 문제 및 단계별 정답/해설';

-- ==============================================================================
-- 2-1. 교과서 문항 보조 테이블 (textbook_questions - 연동 호환용)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.textbook_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject TEXT NOT NULL,
  textbook_name TEXT NOT NULL,
  publisher TEXT,
  unit_code TEXT,
  unit_name TEXT,
  page_number INTEGER DEFAULT 1,
  problem_number INTEGER,
  title TEXT NOT NULL,
  question_text TEXT NOT NULL,
  image_url TEXT,
  solution_steps JSONB DEFAULT '[]'::jsonb,
  final_answer TEXT,
  teacher_tip TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE public.textbook_questions IS '단원별 교과서 문제 목록';

-- ==============================================================================
-- 3. 커뮤니티 Q&A 질문 & 답변 게시판 (community_questions)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.community_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 질문 고유 번호
  author_id TEXT NOT NULL,                                  -- 질문 작성자 계정 ID
  author_name TEXT NOT NULL,                                -- 질문 작성자 닉네임
  author_role TEXT DEFAULT 'student',                       -- 작성자 권한
  author_school TEXT DEFAULT '대구화원고등학교',             -- 작성자 학교
  author_grade TEXT DEFAULT 'high_1',                       -- 작성자 학년
  subject TEXT NOT NULL,                                    -- 과목: 'math' | 'science'
  textbook_ref TEXT,                                        -- 교과서 출처 (예: 비상 교과서 p.42 5번)
  title TEXT NOT NULL,                                      -- 질문 제목
  content TEXT NOT NULL,                                    -- 질문 상세 내용
  image_url TEXT,                                           -- 학생이 업로드한 문제/풀이 사진 (Base64/URL)
  status TEXT DEFAULT 'waiting',                            -- 상태: 'waiting' (답변 대기), 'answered' (선생님 답변 완료)
  likes INTEGER DEFAULT 0,                                  -- 추천수
  teacher_answer JSONB,                                     -- 선생님 맞춤 답변 ({id, teacherName, role, answer, keyConcepts, praiseComment, createdAt})
  created_at TIMESTAMPTZ DEFAULT now()                      -- 질문 등록 일시
);

COMMENT ON TABLE public.community_questions IS '학생 Q&A 질문 및 선생님 맞춤 해설/격려 답변';

-- ==============================================================================
-- 3-1. 심플 Q&A 테이블 (qna_questions - 연동 호환용)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.qna_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  subject TEXT NOT NULL,
  status TEXT DEFAULT '답변대기',
  image_url TEXT,
  answer_content TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ==============================================================================
-- 4. 스마트 오답노트 테이블 (user_wrong_answers)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.user_wrong_answers (
  id TEXT PRIMARY KEY,                                      -- 오답 고유 ID
  user_id TEXT NOT NULL,                                    -- 학생 계정 ID
  quiz_id TEXT,                                             -- 연관된 퀴즈/단원평가 ID
  quiz_title TEXT,                                          -- 퀴즈 제목
  unit_name TEXT,                                           -- 단원명
  subject TEXT NOT NULL,                                    -- 과목 ('math' | 'science')
  question TEXT NOT NULL,                                   -- 문제 지문
  options JSONB DEFAULT '[]'::jsonb,                        -- 객관식 보기 목록
  user_answer_index INTEGER,                                -- 학생이 골랐던 오답 번호
  correct_index INTEGER NOT NULL,                           -- 정답 번호
  explanation TEXT NOT NULL,                                -- 해설 및 정답 풀이
  hint TEXT,                                                -- 문제 힌트
  user_attached_photos JSONB DEFAULT '[]'::jsonb,           -- 학생 본인이 추가로 첨부한 오답 풀이 사진들
  is_reviewed BOOLEAN DEFAULT false,                        -- 다시 풀어서 복습 완료했는지 여부
  review_count INTEGER DEFAULT 0,                           -- 누적 복습 횟수
  my_memo TEXT,                                             -- 학생 개인 오답 분석 메모
  created_at TIMESTAMPTZ DEFAULT now(),                     -- 틀린 날짜
  last_reviewed_at TIMESTAMPTZ                              -- 최근 복습 일시
);

COMMENT ON TABLE public.user_wrong_answers IS '학생별 스마트 오답노트 및 재학습 이력';

-- ==============================================================================
-- 5. 퀴즈/단원평가 응시 기록 (quiz_attempts)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.quiz_attempts (
  id TEXT PRIMARY KEY,                                      -- 응시 기록 고유 ID
  user_id TEXT NOT NULL,                                    -- 학생 계정 ID
  quiz_id TEXT NOT NULL,                                    -- 퀴즈 ID
  quiz_title TEXT NOT NULL,                                 -- 퀴즈 제목
  unit_name TEXT NOT NULL,                                  -- 단원명
  subject TEXT NOT NULL,                                    -- 과목 ('math' | 'science')
  score INTEGER NOT NULL DEFAULT 0,                         -- 맞은 개수
  total_questions INTEGER NOT NULL DEFAULT 0,               -- 전체 문항 수
  percentage INTEGER NOT NULL DEFAULT 0,                    -- 백분율 점수 (0~100)
  completed_at TIMESTAMPTZ DEFAULT now()                    -- 응시 완료 일시
);

COMMENT ON TABLE public.quiz_attempts IS '학생 단원평가 및 3분 스피드 퀴즈 응시 성적표';

-- ==============================================================================
-- 6. 교과서 핵심 개념 정리 (textbook_concepts)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.textbook_concepts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject TEXT NOT NULL,
  grade TEXT DEFAULT 'high_1',
  chapter TEXT NOT NULL,
  unit_name TEXT NOT NULL,
  unit_code TEXT,
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  key_formulas JSONB DEFAULT '[]'::jsonb,
  common_mistakes TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE public.textbook_concepts IS '수학/과학 단원별 핵심 개념 및 공식 정리';

-- ==============================================================================
-- 7. 수학·과학 흥미로운 탐구 포스터 (interesting_facts)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.interesting_facts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject TEXT NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT,
  category TEXT NOT NULL,
  content TEXT NOT NULL,
  poster_image TEXT,
  author_name TEXT DEFAULT '선생님 공식 포스터',
  tags TEXT[] DEFAULT ARRAY[]::TEXT[],
  likes INTEGER DEFAULT 0,
  liked_user_ids TEXT[] DEFAULT ARRAY[]::TEXT[],
  bg_gradient TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE public.interesting_facts IS '수학·과학 실생활 호기심 및 탐구 포스터';

-- ==============================================================================
-- 7-1. 게시글/포스터 테이블 (posters - 연동 호환용)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.posters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  image_url TEXT,
  author TEXT DEFAULT '관리자',
  category TEXT DEFAULT '일반',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ==============================================================================
-- 8. 단원평가 객관식 문제 은행 (test_questions)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.test_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject TEXT NOT NULL,
  unit_code TEXT NOT NULL,
  question_text TEXT NOT NULL,
  options TEXT[] DEFAULT ARRAY[]::TEXT[],
  correct_answer TEXT NOT NULL,
  explanation TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE public.test_questions IS '단원별 3분 스피드 퀴즈/단원평가 문제 은행';

-- ==============================================================================
-- 9. 성능 최적화를 위한 인덱스 생성
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_user_accounts_login_id ON public.user_accounts(login_id);
CREATE INDEX IF NOT EXISTS idx_textbook_problems_subject ON public.textbook_problems(subject, grade);
CREATE INDEX IF NOT EXISTS idx_textbook_problems_unit_code ON public.textbook_problems(unit_code);
CREATE INDEX IF NOT EXISTS idx_textbook_questions_unit ON public.textbook_questions(subject, unit_code);
CREATE INDEX IF NOT EXISTS idx_community_questions_subject ON public.community_questions(subject, status);
CREATE INDEX IF NOT EXISTS idx_community_questions_author ON public.community_questions(author_id);
CREATE INDEX IF NOT EXISTS idx_user_wrong_answers_user_id ON public.user_wrong_answers(user_id);
CREATE INDEX IF NOT EXISTS idx_quiz_attempts_user_id ON public.quiz_attempts(user_id);
CREATE INDEX IF NOT EXISTS idx_interesting_facts_subject ON public.interesting_facts(subject);

-- ==============================================================================
-- 10. 행 단위 보안(RLS, Row Level Security) 및 전체 접근 허용 정책
-- ==============================================================================
ALTER TABLE public.user_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.textbook_problems ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.textbook_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.qna_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_wrong_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.textbook_concepts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interesting_facts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_questions ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  -- user_accounts
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'user_accounts' AND policyname = 'Public Access user_accounts') THEN
    CREATE POLICY "Public Access user_accounts" ON public.user_accounts FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- textbook_problems
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'textbook_problems' AND policyname = 'Public Access textbook_problems') THEN
    CREATE POLICY "Public Access textbook_problems" ON public.textbook_problems FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- textbook_questions
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'textbook_questions' AND policyname = 'Public Access textbook_questions') THEN
    CREATE POLICY "Public Access textbook_questions" ON public.textbook_questions FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- community_questions
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'community_questions' AND policyname = 'Public Access community_questions') THEN
    CREATE POLICY "Public Access community_questions" ON public.community_questions FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- qna_questions
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'qna_questions' AND policyname = 'Public Access qna_questions') THEN
    CREATE POLICY "Public Access qna_questions" ON public.qna_questions FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- user_wrong_answers
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'user_wrong_answers' AND policyname = 'Public Access user_wrong_answers') THEN
    CREATE POLICY "Public Access user_wrong_answers" ON public.user_wrong_answers FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- quiz_attempts
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'quiz_attempts' AND policyname = 'Public Access quiz_attempts') THEN
    CREATE POLICY "Public Access quiz_attempts" ON public.quiz_attempts FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- textbook_concepts
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'textbook_concepts' AND policyname = 'Public Access textbook_concepts') THEN
    CREATE POLICY "Public Access textbook_concepts" ON public.textbook_concepts FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- interesting_facts
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'interesting_facts' AND policyname = 'Public Access interesting_facts') THEN
    CREATE POLICY "Public Access interesting_facts" ON public.interesting_facts FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- posters
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'posters' AND policyname = 'Public Access posters') THEN
    CREATE POLICY "Public Access posters" ON public.posters FOR ALL USING (true) WITH CHECK (true);
  END IF;

  -- test_questions
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'test_questions' AND policyname = 'Public Access test_questions') THEN
    CREATE POLICY "Public Access test_questions" ON public.test_questions FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ==============================================================================
-- 11. 초기 관리자/선생님 테스트 계정 생성 (선택 사항)
-- ==============================================================================
INSERT INTO public.user_accounts (id, login_id, password_hash, role, nickname, school_name, grade)
VALUES 
  ('user-admin-default', 'admin', 'admin1234', 'admin', '총괄관리자', '대구화원고등학교', 'high_1'),
  ('user-teacher-math', 'teacher', 'teacher1234', 'teacher', '김선생님', '대구화원고등학교', 'high_1')
ON CONFLICT (login_id) DO NOTHING;

-- ==============================================================================
-- 12. 실시간(Realtime) 구독 활성화
-- ==============================================================================
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.community_questions;
  ALTER PUBLICATION supabase_realtime ADD TABLE public.textbook_problems;
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;

-- ==============================================================================
-- 13. 고화질 사진 저장을 위한 Supabase 스토리지 버킷 자동 생성
-- ==============================================================================
INSERT INTO storage.buckets (id, name, public) 
VALUES 
  ('problem-images', 'problem-images', true),
  ('qna-images', 'qna-images', true),
  ('wrong-note-images', 'wrong-note-images', true)
ON CONFLICT (id) DO NOTHING;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Public Access for problem-images') THEN
    CREATE POLICY "Public Access for problem-images" ON storage.objects FOR ALL USING (bucket_id = 'problem-images') WITH CHECK (bucket_id = 'problem-images');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Public Access for qna-images') THEN
    CREATE POLICY "Public Access for qna-images" ON storage.objects FOR ALL USING (bucket_id = 'qna-images') WITH CHECK (bucket_id = 'qna-images');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Public Access for wrong-note-images') THEN
    CREATE POLICY "Public Access for wrong-note-images" ON storage.objects FOR ALL USING (bucket_id = 'wrong-note-images') WITH CHECK (bucket_id = 'wrong-note-images');
  END IF;
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;
